-- MySQL Script generated by MySQL Workbench
-- 08/31/16 18:26:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema neldam_nr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema neldam_nr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `neldam_nr` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `neldam_nr` ;

-- -----------------------------------------------------
-- Table `neldam_nr`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neldam_nr`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `active_season` INT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `mail` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neldam_nr`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neldam_nr`.`user_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neldam_nr`.`seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neldam_nr`.`seasons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `description` VARCHAR(200) NULL,
  `fields_number` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seasons_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_seasons_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `neldam_nr`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
