-- MySQL Script generated by MySQL Workbench
-- 08/31/16 23:26:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema neldam_an
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema neldam_an
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `neldam_an` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `neldam_an` ;

-- -----------------------------------------------------
-- Table `neldam_an`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neldam_an`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `active_season` INT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `mail` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neldam_an`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neldam_an`.`user_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neldam_an`.`seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neldam_an`.`seasons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(200) NULL,
  `fields_number` INT NULL,
  `cost` REAL NULL DEFAULT 0,
  `profit` REAL NULL DEFAULT 0,
  `operations_number` INT NULL DEFAULT 0,
  `other_season_costs` REAL NULL DEFAULT 0,
  `other_season_profit` REAL NULL DEFAULT 0,
  `user_id` INT NOT NULL,
  `fields_size` REAL NULL DEFAULT 0,
  `operations_cost` REAL NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_seasons_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_seasons_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `neldam_an`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neldam_an`.`fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neldam_an`.`fields` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `size` REAL NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fields_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_fields_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `neldam_an`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neldam_an`.`season_fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neldam_an`.`season_fields` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `season_id` INT NOT NULL,
  `field_id` INT NOT NULL,
  `plant` VARCHAR(100) NULL,
  `variety` VARCHAR(100) NULL,
  `sowing_cost` REAL NULL DEFAULT 0,
  `lease_cost` REAL NULL DEFAULT 0,
  `sowing_type` ENUM('PRO_HA', 'PRO_FIELD') NULL,
  `leasing_cost` ENUM('PRO_HA', 'PRO_FIELD') NULL,
  `tons_pro_ha` REAL NULL DEFAULT 0,
  `tone_price` REAL NULL,
  `tax_cost` REAL NULL DEFAULT 0,
  `tax_type` ENUM('PRO_HA', 'PRO_FIELD') NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_season_fields_seasons1_idx` (`season_id` ASC),
  INDEX `fk_season_fields_fields1_idx` (`field_id` ASC),
  CONSTRAINT `fk_season_fields_seasons1`
    FOREIGN KEY (`season_id`)
    REFERENCES `neldam_an`.`seasons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_season_fields_fields1`
    FOREIGN KEY (`field_id`)
    REFERENCES `neldam_an`.`fields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neldam_an`.`operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neldam_an`.`operations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `pesticide_name` VARCHAR(100) NOT NULL,
  `dose` REAL NULL,
  `dose_type` ENUM('KG_PRO_HA', 'L_PRO_HA') NULL,
  `operation_reason` VARCHAR(200) NULL,
  `eko_harm` REAL NULL DEFAULT 0,
  `cost` REAL NULL,
  `cost_type` ENUM('PRO_HA', 'PRO_L', 'PRO_KG', 'PRO_TON', 'PRO_FIELD') NULL,
  `comment` VARCHAR(200) NULL,
  `season_field_id` INT NOT NULL,
  `operation_type` ENUM('PROTECTION', 'FERTILIZER') NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_protection_operations_season_fields1_idx` (`season_field_id` ASC),
  CONSTRAINT `fk_protection_operations_season_fields1`
    FOREIGN KEY (`season_field_id`)
    REFERENCES `neldam_an`.`season_fields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neldam_an`.`other_costs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neldam_an`.`other_costs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cost` REAL NOT NULL DEFAULT 0,
  `cost_type` ENUM('PRO_HA', 'PRO_FIELD') NOT NULL,
  `date` DATE NOT NULL,
  `season_field_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_other_costs_season_fields1_idx` (`season_field_id` ASC),
  CONSTRAINT `fk_other_costs_season_fields1`
    FOREIGN KEY (`season_field_id`)
    REFERENCES `neldam_an`.`season_fields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neldam_an`.`other_profit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neldam_an`.`other_profit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profit` REAL NULL DEFAULT 0,
  `profit_type` ENUM('PRO_HA', 'PRO_FIELD') NULL,
  `date` DATE NULL,
  `season_field_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_other_profit_season_fields1_idx` (`season_field_id` ASC),
  CONSTRAINT `fk_other_profit_season_fields1`
    FOREIGN KEY (`season_field_id`)
    REFERENCES `neldam_an`.`season_fields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `neldam_an`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `neldam_an`;
INSERT INTO `neldam_an`.`users` (`id`, `username`, `password`, `enabled`, `active_season`, `first_name`, `last_name`, `mail`) VALUES (DEFAULT, 'neldam', 'puma1234', 1, 1, 'Mateusz', 'Gocz', 'msgocz@gmail.com');
INSERT INTO `neldam_an`.`users` (`id`, `username`, `password`, `enabled`, `active_season`, `first_name`, `last_name`, `mail`) VALUES (DEFAULT, 'test', 'test', 1, 2, 'Jan', 'Kowalski', 'kow@mail.pl');

COMMIT;


-- -----------------------------------------------------
-- Data for table `neldam_an`.`user_roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `neldam_an`;
INSERT INTO `neldam_an`.`user_roles` (`id`, `role`, `username`) VALUES (DEFAULT, 'ROLE_ADMIN', 'neldam');
INSERT INTO `neldam_an`.`user_roles` (`id`, `role`, `username`) VALUES (DEFAULT, 'ROLE_USER', 'test');

COMMIT;


-- -----------------------------------------------------
-- Data for table `neldam_an`.`seasons`
-- -----------------------------------------------------
START TRANSACTION;
USE `neldam_an`;
INSERT INTO `neldam_an`.`seasons` (`id`, `description`, `fields_number`, `cost`, `profit`, `operations_number`, `other_season_costs`, `other_season_profit`, `user_id`, `fields_size`, `operations_cost`) VALUES (DEFAULT, 'Sezon 2015/260', 22, 0, 0, 0, 0, 0, 1, 0, 0);
INSERT INTO `neldam_an`.`seasons` (`id`, `description`, `fields_number`, `cost`, `profit`, `operations_number`, `other_season_costs`, `other_season_profit`, `user_id`, `fields_size`, `operations_cost`) VALUES (DEFAULT, 'Sezon 2014/2-15', 4, 0, 0, 0, 0, 0, 2, 0, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `neldam_an`.`fields`
-- -----------------------------------------------------
START TRANSACTION;
USE `neldam_an`;
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR42', 'Pole 1', 1.31, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR43', 'Pole 2', 2.41, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR44', 'Pole 3', 1.23, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR425', 'Pole 4', 5.4, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR32', 'Pole 6', 12.4, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR421', 'Pole 5', 24.4, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR445', 'Pole 7', 3.5, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WRS2', 'Pole 8', 5.6, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR52', 'Pole 10', 4.2, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR42X', 'Pole 9', 3.53, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR432', 'Pole 11', 8.54, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WRD32; ES124', 'Pole 12', 6.7, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR446', 'Pole 13', 4.3, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR4285', 'Pole 14', 3.2, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR463', 'Pole 15', 1.6, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR4225', 'Pole 16', 3.552, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR422542', 'Pole 17', 5.7, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR73', 'Pole 18', .7, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR162', 'Pole 19', 3.7, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR42673', 'Pole 20', 3.67, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR4273', 'Pole 21', 4.63, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR495', 'Pole 22', .89, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR43423', 'Pole 23', 5.83, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR95434', 'Pole 24', 7.3, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR4263', 'Pole 25', 8.432, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR45364', 'Pole 27', 5.3, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'WR3262', 'Pole 28', 2.2, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'QWR113', 'Pole 29', 4.1, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'QWR1142', 'Pole 29', 4.25, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'QWR623', 'Pole 30', 2.52, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'QWR642', 'Pole 31', 5, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'QWR83', 'Pole 32', 5.52, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'QWR14', 'Pole 34', .52, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'QWR53', 'Pole 33', 52, 1);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (, 'RT342', 'Pole test 1', 10, 2);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'RT343', 'Pole test 2', 1, 2);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'RT345', 'Pole test 3', 2, 2);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'RT346', 'Pole test 5', 3, 2);
INSERT INTO `neldam_an`.`fields` (`id`, `number`, `description`, `size`, `user_id`) VALUES (DEFAULT, 'RT3426', 'Pole test 113', 4, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `neldam_an`.`season_fields`
-- -----------------------------------------------------
START TRANSACTION;
USE `neldam_an`;
INSERT INTO `neldam_an`.`season_fields` (`id`, `season_id`, `field_id`, `plant`, `variety`, `sowing_cost`, `lease_cost`, `sowing_type`, `leasing_cost`, `tons_pro_ha`, `tone_price`, `tax_cost`, `tax_type`, `user_id`) VALUES (DEFAULT, 1, 1, 'Rzepak', 'KWS 24 Rasp', 0, 0, 'PRO_HA', 'PRO_HA', 0, 0, 0, 'PRO_HA', 0);
INSERT INTO `neldam_an`.`season_fields` (`id`, `season_id`, `field_id`, `plant`, `variety`, `sowing_cost`, `lease_cost`, `sowing_type`, `leasing_cost`, `tons_pro_ha`, `tone_price`, `tax_cost`, `tax_type`, `user_id`) VALUES (0, DEFAULT, DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DEFAULT);

COMMIT;

